final code = {
  "theme":
      """<code class=" language-dart"><span class="token function"><span class="n">Theme</span></span><span class="token punctuation"><span class="o">(</span></span>
  <span class="token comment" spellcheck="true"><span class="c1">// Create a unique theme with "ThemeData"</span></span>
  <span class="nl">data<span class="token punctuation">:</span></span><span class="token punctuation"></span> <span class="token function"><span class="n">ThemeData</span></span><span class="token punctuation"><span class="o">(</span></span>
    <span class="nl">accentColor<span class="token punctuation">:</span></span><span class="token punctuation"></span> <span class="n">Colors</span><span class="token punctuation"><span class="o">.</span></span><span class="na">yellow</span><span class="token punctuation"><span class="o">,</span></span>
  <span class="token punctuation"></span><span class="o"><span class="token punctuation">)</span><span class="token punctuation">,</span></span><span class="token punctuation"></span>
  <span class="nl">child<span class="token punctuation">:</span></span><span class="token punctuation"></span> <span class="token function"><span class="n">FloatingActionButton</span></span><span class="token punctuation"><span class="o">(</span></span>
    <span class="nl">onPressed<span class="token punctuation">:</span></span><span class="token punctuation"></span> <span class="token punctuation"></span><span class="o"><span class="token punctuation">(</span><span class="token punctuation">)</span></span><span class="token punctuation"></span> <span class="token punctuation"></span><span class="o"><span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">,</span></span><span class="token punctuation"></span>
    <span class="nl">child<span class="token punctuation">:</span></span><span class="token punctuation"></span> <span class="token function"><span class="n">Icon</span></span><span class="token punctuation"><span class="o">(</span></span><span class="n">Icons</span><span class="token punctuation"><span class="o">.</span></span><span class="na">add</span><span class="token punctuation"></span><span class="o"><span class="token punctuation">)</span><span class="token punctuation">,</span></span><span class="token punctuation"></span>
  <span class="token punctuation"></span><span class="o"><span class="token punctuation">)</span><span class="token punctuation">,</span></span><span class="token punctuation"></span>
<span class="token punctuation"></span><span class="o"><span class="token punctuation">)</span><span class="token punctuation">;</span></span><span class="token punctuation"></span>
</code>""",
  "main_theme":
      """<code class=" language-dart"><span class="token function"><span class="n">MaterialApp</span></span><span class="token punctuation"><span class="o">(</span></span>
  <span class="nl">title<span class="token punctuation">:</span></span><span class="token punctuation"></span> <span class="n">title</span><span class="token punctuation"><span class="o">,</span></span>
  <span class="nl">theme<span class="token punctuation">:</span></span><span class="token punctuation"></span> <span class="token function"><span class="n">ThemeData</span></span><span class="token punctuation"><span class="o">(</span></span>
    <span class="nl">brightness<span class="token punctuation">:</span></span><span class="token punctuation"></span> <span class="n">Brightness</span><span class="token punctuation"><span class="o">.</span></span><span class="na">dark</span><span class="token punctuation"><span class="o">,</span></span>
    <span class="nl">primaryColor<span class="token punctuation">:</span></span><span class="token punctuation"></span> <span class="n">Colors</span><span class="token punctuation"><span class="o">.</span></span><span class="na">lightBlue</span><span class="token punctuation"><span class="o">[</span></span><span class="token number"><span class="mi">800</span></span><span class="token punctuation"></span><span class="o"><span class="token punctuation">]</span><span class="token punctuation">,</span></span><span class="token punctuation"></span>
    <span class="nl">accentColor<span class="token punctuation">:</span></span><span class="token punctuation"></span> <span class="n">Colors</span><span class="token punctuation"><span class="o">.</span></span><span class="na">cyan</span><span class="token punctuation"><span class="o">[</span></span><span class="token number"><span class="mi">600</span></span><span class="token punctuation"></span><span class="o"><span class="token punctuation">]</span><span class="token punctuation">,</span></span><span class="token punctuation"></span>
  <span class="token punctuation"></span><span class="o"><span class="token punctuation">)</span><span class="token punctuation">,</span></span><span class="token punctuation"></span>
<span class="token punctuation"></span><span class="o"><span class="token punctuation">)</span><span class="token punctuation">;</span></span><span class="token punctuation"></span>
</code>"""
};
